{"message":"user with this data didn`t exist","time":1682690610666,"code":404,"stackTrace":"UserNotFoundError: user with this data didn`t exist\n    at _callee2$ (/server/src/controllers/queries/userQueries.js:18:11)\n    at tryCatch (/server/node_modules/regenerator-runtime/runtime.js:63:40)\n    at Generator.invoke [as _invoke] (/server/node_modules/regenerator-runtime/runtime.js:293:22)\n    at Generator.next (/server/node_modules/regenerator-runtime/runtime.js:118:21)\n    at asyncGeneratorStep (/server/src/controllers/queries/userQueries.js:15:103)\n    at _next (/server/src/controllers/queries/userQueries.js:17:194)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}{"message":"user with this data didn`t exist","time":1682690716334,"code":404,"stackTrace":"UserNotFoundError: user with this data didn`t exist\n    at _callee2$ (/server/src/controllers/queries/userQueries.js:18:11)\n    at tryCatch (/server/node_modules/regenerator-runtime/runtime.js:63:40)\n    at Generator.invoke [as _invoke] (/server/node_modules/regenerator-runtime/runtime.js:293:22)\n    at Generator.next (/server/node_modules/regenerator-runtime/runtime.js:118:21)\n    at asyncGeneratorStep (/server/src/controllers/queries/userQueries.js:15:103)\n    at _next (/server/src/controllers/queries/userQueries.js:17:194)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}